### ISSUE TITLE
ImportError: cannot import name 'pgoapi' 

### ISSUE THREAD

**Issue by medienoekonom** [cqian19/PokeGo-Idle#2]
hi there, 

it seems somethings missing what can i do? 

![image](https://cloud.githubusercontent.com/assets/20904559/17618580/dc818fda-6080-11e6-8ea2-fa0782e070d5.png)

**Comment by cqian19** [comment]
A few files got dropped from the zip. I'm on it right now.

**Comment by cqian19** [comment]
New zip is up although there are definitely other issues. I'm going to get some rest now and address them tomorrow.
